{% set name = "tox-current-env" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tox-current-env-{{ version }}.tar.gz
  sha256: 5b05d7a169e323ca73c8bacd90cfcfe38e2672b705f944f94d1d6c0f56f31c51

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - tox >=3.24

test:
  imports:
    - tox_current_env
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fedora-python/tox-current-env
  summary: Use current environment instead of virtualenv for tox testenvs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - millsks
