{% set name = "tox-current-env" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 599fc68afe017377e31b4a430114db436efab46bf74148f1259c912e85600924

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - tox >=3.24

test:
  imports:
    - tox_current_env
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fedora-python/tox-current-env
  summary: Use current environment instead of virtualenv for tox testenvs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wshanks
    - millsks
