{% set name = "tox-current-env" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tox-current-env-{{ version }}.tar.gz
  sha256: aaee9e1bc204788065402827c75885ad678a1bec073cf2c4e2cecd1b898d520f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - tox >=3.24

test:
  imports:
    - tox_current_env
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fedora-python/tox-current-env
  summary: Use current environment instead of virtualenv for tox testenvs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - millsks
